version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        secretKey: climatewathisanawesomeprojectandtrackingtoo
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - POSTGRES_URL=postgres://postgres:example@postgres:5432/cw_south_africa
      - RAILS_SERVE_STATIC_FILES=true
      - RACK_ENV=production
      - RAILS_ENV=production
      - REDIS_SERVER=redis://localhost:6379
    restart: always
    container_name: cw-south-africa
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cw_south_africa

  redis:
    image: redis:3.2.5
    ports:
      - "6379"
