version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        secretKey: 1234567890
    ports:
      - "3000:3000"
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=3000
      - POSTGRES_URL=postgres://postgres:example@postgres:5432/cw-south-africa
      - RAILS_SERVE_STATIC_FILES="true"
      - RAILS_LOG_TO_STDOUT="true"
      - HTTP_AUTH_USERNAME=admin
      - HTTP_AUTH_PASSWORD=admin
    restart: always
    container_name: cw-south-africa
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/cw-south-africa

  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cw-south-africa
