apiVersion: v1
kind: Service
metadata:
  namespace: climate-watch
  labels:
    name: south-africa-platform-staging
  name: south-africa-platform-staging
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    name: south-africa-platform-staging
