platforms:
  - name: south_africa_platform
    sections:
      - name: historical_emissions
        importer: ImportHistoricalEmissions
        datasets:
          - historical_emissions_metadata_sectors
          - historical_emissions_data
      - name: metadata
        importer: ImportDataSource
        datasets:
          - data_sources
      - name: financial_resources
        importer: ImportFinancialResource
        datasets:
          - support_needs
          - support_received
          - financial_indicators
      - name: projected_emissions
        importer: ImportProjectedEmissions
        datasets:
          - projected_emissions
          - projected_emissions_metadata
      - name: inventory_improvement
        importer: ImportInventoryImprovement
        datasets:
          - inventory_improvement_projects
      - name: mitigation_actions
        importer: ImportMitigation
        datasets:
          - mitigation_actions
          - mitigation_effects
          - mitigation_indicators
          - flagship_programmes
          - flagship_components
      - name: national_circumstances
        importer: ImportNationalCircumstances
        datasets:
          - priorities
          - national_circumstances_indicators
          - national_circumstances
