default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres

development:
  <<: *default
  url: <%= ENV['POSTGRES_URL'] %>

test:
  <<: *default
  database: cw-south-africa_test

production:
  <<: *default
  url: <%= ENV['POSTGRES_URL'] %>

# Config for second shared database
secondbase:
  production:
    adapter: postgresql
    encoding: unicode
    database: climate-watch-shared
    url: <%= ENV['SHARED_POSTGRES_URL'] %>
  development:
    adapter: postgresql
    encoding: unicode
    database: climate-watch-shared_development
    url: <%= ENV['SHARED_POSTGRES_URL'] %>
  test:
    adapter: postgresql
    encoding: unicode
    database: climate-watch-shared_test
