sections:
  - name: intro
    title:
    description: The <b>South Africa’s Biennial Update Report</b> offers open data, visualizations and analysis to help you gather insights on South Africa’s climate progress. It is an an important part of the National Climate Change Monitoring and Evaluation (M&E) System established as part of the national efforts to track South Africa’s overall transition to a low carbon and climate resilient society and economy.
  - name: ndc_submission
    title: South Africa National Determined Contribution (NDC) pledge and ambition
    description: Under South Africa’s NDC, GHG emissions will peak between 2020 and 2025, plateau for approximately a decade, landing in the range of 398-614 MtCO2eq as defined by national policy, and decline in absolute terms thereafter.<br><br>The adaptation component of South Africa’s NDC will address adaptation through six goals, underpinned by key elements of adaptation planning, pricing of adaptation investment requirements, equity, and means of implementation.
  - name: historical_emissions
    title: Historical Emissions
    description: "South Africa’s National GHG inventory for the period 2000-2014 was compiled according to the IPCC-2006 guidelines and covers four emission sectors: Energy; Industrial Processes and Product Use; Agriculture, Forestry and Other Land Use; and Waste."
  - name: flagship_programmes
    title: Flagship Programmes
    description: The Climate Change Flagship Programmes are strategic measures implemented by the South African government to trigger a large-scale transition to a low-carbon economy and create a more climate-resilient South Africa. They signal climate change investment priorities and provide the certainty needed to stimulate further investment.
  - name: national_circumstances
    title: National Circumstances
    description: This section provides context for South Africa’s climate change response, including information on provincial development priorities, population, economy, energy, and climate risks from natural disasters.
  - name: provincial
    title: Provincial Development Priorities
    description:
  - name: population
    title: Population
    description:
  - name: economy
    title: Economy
    description:
  - name: energy
    title: Energy supply
    description:
  - name: natural-disasters
    title: Natural Disasters
    description:
  - name: ghg_emissions
    title: GHG Emissions
    description: This section provides information on South Africa’s GHG inventory, the programmes it’s implementing to improve the quality of future national GHG inventories and possible future emissions pathways under different mitigation scenarios.
  - name: historical
    title: Historical emissions
    description:
  - name: inventory
    title: GHG Inventory Improvement Programmes
    description:
  - name: projected-emissions
    title: Projected Emissions
    description:
  - name: mitigation_actions_section
    title: Mitigation Actions
    description: South Africa’s approach to mitigation is informed by its contribution to the international effort to reduce global GHG emissions and its successful management of development and poverty eradication challenges. South Africa is committed to addressing climate change based on science and equity and to work with others to ensure global average temperature increases are kept well below 2°C and potentially 1.5°C above pre-industrial levels. Global average temperature increase of 2°C translates to up to 4°C for South Africa by the end of the century. South Africa’s mitigation action will be accessed against its commitment to reduce emissions to a range between 398 and 614 CO2-eq by 2030 and 2050, as defined in national policy.
  - name: mitigation-actions
    title: Mitigation Actions
    description:
  - name: mitigation-effects
    title: Mitigation Effects
    description:
  - name: flagship-programmes
    title: Flagship Programmes
    description:
  - name: financial_resources
    title: Financial Resources
    description: This section shows climate finance provided from multilateral, bilateral, and domestic sources as well as remaining financial and non-financial support needs.
  - name: support-received
    title: Support Received
    description:
  - name: support-needed
    title: Support Needed
    description:
