sections:
  - name: intro
    subsections:
      - name: ndc_submission
      - name: historical_emissions
      - name: flagship_programmes
  - name: national_circumstances
    subsections: 
      - name: provincial
      - name: population
      - name: economy
      - name: energy
      - name: natural-disasters
  - name: ghg_emissions
    subsections:
      - name: historical
      - name: inventory
      - name: projected-emissions
  - name: mitigation_actions_section
    subsections:
      - name: mitigation-actions
      - name: mitigation-effects
      - name: flagship-programmes
  - name: financial_resources
    subsections: 
      - name: support-received
      - name: support-needed