apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: climate-watch
  labels:
    name: south-africa-platform
  name: south-africa-platform
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: south-africa-platform
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - webapps
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - south-africa-platform
              topologyKey: kubernetes.io/hostname
      containers:
      - name: south-africa-platform
        image: vizzuality/south-africa-platform
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
        env:
          - name: CW_FILES_PREFIX
            value: 'climatewatch.org/www.climatewatch.org/south-africa/'
          - name: RACK_ENV
            value: production
          - name: RAILS_ENV
            value: production
          - name: PORT
            value: "3000"
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"
          - name: PASSWORD_PROTECT
            value: "false"
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
          - name: HTTP_AUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: CW_AUTH_USERNAME
          - name: HTTP_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: CW_AUTH_PASSWORD
          - name: POSTGRES_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: CW_POSTGRES_URL
          - name: S3_BUCKET_NAME
            value: "wri-sites"
          - name: AWS_REGION
            value: "eu-west-1"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: CW_PLATFORMS_S3_ACCESS_KEY
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: CW_PLATFORMS_S3_SECRET_ACCESS_KEY

        ports:
          - containerPort: 3000

      restartPolicy: Always
